; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+05 on Sat Sep 25 2021 10:00:12 GMT+0100 (British Summer Time)
M561 ; clear any bed transform
;G29  ; probe the bed and enable compensation


