; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+08 on Fri Nov 12 2021 20:40:12 GMT+0000 (Greenwich Mean Time)
M98 P"homex.g"
M98 P"homey.g"
M98 P"homez.g"

